// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package flatfilemanager.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import flatfilemanager.implementation.FileHandler;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ExportToFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject ExportObject;
	private IMendixObject __ExportConfig;
	private flatfilemanager.proxies.TemplateSet ExportConfig;
	private IMendixObject __ExportFile;
	private system.proxies.FileDocument ExportFile;
	private java.lang.String Filename;

	public ExportToFile(IContext context, IMendixObject ExportObject, IMendixObject ExportConfig, IMendixObject ExportFile, java.lang.String Filename)
	{
		super(context);
		this.ExportObject = ExportObject;
		this.__ExportConfig = ExportConfig;
		this.__ExportFile = ExportFile;
		this.Filename = Filename;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.ExportConfig = __ExportConfig == null ? null : flatfilemanager.proxies.TemplateSet.initialize(getContext(), __ExportConfig);

		this.ExportFile = __ExportFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __ExportFile);

		// BEGIN USER CODE
		FileHandler fileHandler = new FileHandler(this.getContext(), this.ExportConfig.getMendixObject(), this.ExportObject);

		Core.storeFileDocumentContent(this.getContext(), this.ExportFile.getMendixObject(), this.Filename, fileHandler.exportToFile());


		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ExportToFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
