// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package flatfilemanager.actions;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.apache.commons.io.IOUtils;
import system.proxies.FileDocument;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * zips a filedocument into a new filedocument
 */
public class Zip_FileDocument extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __document;
	private system.proxies.FileDocument document;

	public Zip_FileDocument(IContext context, IMendixObject document)
	{
		super(context);
		this.__document = document;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.document = __document == null ? null : system.proxies.FileDocument.initialize(getContext(), __document);

		// BEGIN USER CODE
		ByteArrayOutputStream zipOut = new ByteArrayOutputStream();
        ZipOutputStream zipfile = new ZipOutputStream(zipOut);
        zipfile.putNextEntry(new ZipEntry(this.document.getName()));
        IOUtils.copy(Core.getFileDocumentContent(this.getContext(), this.document.getMendixObject()), zipfile);
        zipfile.close();

        
        IMendixObject target = Core.instantiate(getContext(), FileDocument.getType());
        Core.storeFileDocumentContent(getContext(), 
        		target, 
        		this.document.getName() + ".zip", 
        		new ByteArrayInputStream(zipOut.toByteArray()));
        Core.commit(this.getContext(), target);
        
        return target;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Zip_FileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
